version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 32
  identical-code:
    enabled: true
    config:
      threshold: 32

plugins:
  duplication: { enabled: true }
  fixme: { enabled: true }
  pep8: { enabled: true }
  radon: { enabled: true }
  sonar-python: { enabled: true }
  semgrep: { enabled: false }

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*.pyc"
- "**/__pypackages__/"
- "**/.venv/"

